name: Ecommerce API CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore Ecommerce.sln

      # Build solution
      - name: Build
        run: dotnet build Ecommerce.sln --no-restore --configuration Release

      # Run tests
      - name: Test
        run: dotnet test Ecommerce.sln --no-build --verbosity normal
